---
version: 2.1

commands:
  test:
    steps:
      - run: node --version
      - run: npm --version
      - run: openssl version
      - checkout
      - run: npm i
      - run: npm test

jobs:
  node-v10: { docker: [{ image: circleci/node:10 }], steps: [ test ]}
  node-v11: { docker: [{ image: circleci/node:11 }], steps: [ test ]}

workflows:
  test-suite:
    jobs:
      - node-v10
      - node-v11
